CREATE TABLE FARIN_StokBuku(
       StokBukuId VARCHAR(26) NOT NULL CONSTRAINT FARIN_StokBuku_StokBukuId DEFAULT(''),
       StokLayerId VARCHAR(26) NOT NULL CONSTRAINT FARIN_StokBuku_StokLayerId DEFAULT(''),
       NoUrut INT NOT NULL CONSTRAINT FARIN_StokBuku_NoUrut DEFAULT(0),

       BrgId VARCHAR(13) NOT NULL CONSTRAINT FARIN_StokBuku_BrgId DEFAULT(''),
       LayananId VARCHAR(5) NOT NULL CONSTRAINT FARIN_StokBuku_LayananId DEFAULT(''),

       PurchaseId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokBuku_PurchaseId DEFAULT(''),
       ReceiveId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokBuku_ReceiveId DEFAULT(''),
       ExpDate DATETIME NOT NULL CONSTRAINT DF_FARIN_StokBuku_ExpDate DEFAULT('3000-01-01'),
       BatchNo VARCHAR(20) NOT NULL CONSTRAINT DF_FARIN_StokBuku_BatchNo DEFAULT(''),

       QtyIn INT NOT NULL CONSTRAINT FARIN_StokBuku_QtyIn DEFAULT(0),
       QtyOut INT NOT NULL CONSTRAINT FARIN_StokBuku_QtyOut DEFAULT(0),
       Hpp DECIMAL(18, 2) NOT NULL CONSTRAINT FARIN_StokBuku_Hpp DEFAULT(0),

       TrsReffId VARCHAR(26) NOT NULL CONSTRAINT FARIN_StokBuku_TrsReffId DEFAULT(''),
       TrsReffDate DATETIME NOT NULL CONSTRAINT FARIN_StokBuku_TrsReffDate DEFAULT('3000-01-01'),
       UseCase VARCHAR(20) NOT NULL CONSTRAINT FARIN_StokBuku_UseCase DEFAULT(''),
       EntryDate DATETIME NOT NULL CONSTRAINT FARIN_StokBuku_EntryDate DEFAULT('3000-01-01'),

       CONSTRAINT PK_FARIN_StokBuku PRIMARY KEY CLUSTERED (StokBukuId)
)
GO

CREATE INDEX IX_FARIN_StokBuku_StokLayerId ON FARIN_StokBuku (StokLayerId, StokBukuId)
GO