CREATE TABLE FARIN_StokLayer(
    StokLayerId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokLayer_StokLayerId DEFAULT(''),
    BrgId VARCHAR(13) NOT NULL CONSTRAINT DF_FARIN_StokLayer_BrgId DEFAULT(''),
    LayananId VARCHAR(5) NOT NULL CONSTRAINT DF_FARIN_StokLayer_LayananId DEFAULT(''),
    
    TrsReffInId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokLayer_TrsReffInId DEFAULT(''),
    TrsReffInDate DATETIME NOT NULL CONSTRAINT DF_FARIN_StokLayer_TrsReffInDate DEFAULT('3000-01-01'),
    
    PurchaseId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokLayer_PurchaseId DEFAULT(''),
    ReceiveId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokLayer_ReceiveId DEFAULT(''),
    ExpDate DATETIME NOT NULL CONSTRAINT DF_FARIN_StokLayer_ExpDate DEFAULT('3000-01-01'),
    BatchNo VARCHAR(20) NOT NULL CONSTRAINT DF_FARIN_StokLayer_BatchNo DEFAULT(''),
    
    QtyIn INT NOT NULL CONSTRAINT DF_FARIN_StokLayer_QtyIn DEFAULT(0),
    QtySisa INT NOT NULL CONSTRAINT DF_FARIN_StokLayer_QtySisa DEFAULT(0),
    Hpp DECIMAL(18,2) NOT NULL CONSTRAINT DF_FARIN_StokLayer_Hpp DEFAULT(0),
    
    CONSTRAINT PK_FARIN_StokLayer PRIMARY KEY CLUSTERED (StokLayerId)
)
GO

CREATE INDEX IX_FARIN_StokLayer_BrgLynExpDate 
    ON FARIN_StokLayer (BrgId, LayananId, ExpDate, StokLayerId)
    WITH(FILLFACTOR = 90)
GO