CREATE TABLE FARIN_Stok(
    BrgId VARCHAR(13) NOT NULL CONSTRAINT DF_FARIN_Stok_BrgId DEFAULT(''),
    LayananId VARCHAR(5) NOT NULL CONSTRAINT DF_FARIN_Stok_LayananId DEFAULT(''),
    Qty INT NOT NULL CONSTRAINT DF_FARIN_Stok_Qty DEFAULT(''),
    Satuan VARCHAR(10) NOT NULL CONSTRAINT DF_FARIN_Stok_Satuan DEFAULT(''),
    
    CONSTRAINT PK_FARIN_Stok PRIMARY KEY CLUSTERED (BrgId, LayananId)
)