CREATE TABLE FARIN_OrderMutasiItem
(
	OrderMutasiId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiItem_OrderMutasiId DEFAULT(''),
	NoUrut INT NOT NULL CONSTRAINT DF_FARIN_OrderMutasiItem_NoUrut DEFAULT(0),
	BrgId VARCHAR(13) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiItem_BrgId DEFAULT(''),
	BrgName VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiItem_BrgName DEFAULT(''),
	Qty DECIMAL(18,0) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiItem_Qty DEFAULT(0),
	SatuanId VARCHAR(13) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiItem_SatuanId DEFAULT(''),
	SatuanName VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiItem_SatuanName DEFAULT(''),

	CONSTRAINT PK_FARIN_OrderMutasiItem PRIMARY KEY CLUSTERED(OrderMutasiId, BrgId)
)
GO
