CREATE TABLE FARIN_OrderMutasi
(
	OrderMutasiId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_OrderMutasiId DEFAULT(''),
	OrderMutasiDate DATETIME NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_OrderMutasiDate DEFAULT('3000-01-01'),
	State INT NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_State DEFAULT(0),

	LayananOrderId VARCHAR(5) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_LayananOrderId DEFAULT(''),
	LayananOrderName VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_LayananOrderName DEFAULT(''),
	LayananTujuanId VARCHAR(5) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_LayananTujuanId DEFAULT(''),
	LayananTujuanName VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_LayananTujuanName DEFAULT(''),
	OrderNote VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_OrderNote DEFAULT(''),

	UserCreateId VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_UserCreateId DEFAULT(''),
	TglJamCreate DATETIME NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_TglJamCreate DEFAULT('1900-01-01T00:00:00'),
	UserModifyId VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_UserUpdateId DEFAULT(''),
	TglJamModify DATETIME NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_TglJamUpdate DEFAULT('1900-01-01T00:00:00'),
	UserVoidId VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_UserVoidId DEFAULT(''),
	TglJamVoid DATETIME NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_TglJamVoid DEFAULT('1900-01-01T00:00:00')

	CONSTRAINT PK_FARIN_OrderMutasi PRIMARY KEY CLUSTERED(OrderMutasiId)
)
GO
