CREATE TABLE FARIN_OrderMutasi
(
	OrderMutasiId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_OrderMutasiId DEFAULT(''),
	OrderMutasiDate DATETIME NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_OrderMutasiDate DEFAULT('3000-01-01'),
	State INT NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_State DEFAULT(0),

	LayananOrderId VARCHAR(5) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_LayananOrderId DEFAULT(''),
	LayananOrderName VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_LayananOrderName DEFAULT(''),
	LayananTujuanId VARCHAR(5) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_LayananTujuanId DEFAULT(''),
	LayananTujuanName VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_LayananTujuanName DEFAULT(''),
	OrderNote VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_OrderNote DEFAULT(''),

	CrtUser VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_CrtUser DEFAULT(''),
	CrtDate DATETIME NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_CrtDate DEFAULT('3000-01-01'),
	UpdUser VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_UpdUser DEFAULT(''),
	UpdDate DATETIME NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_UpdDate DEFAULT('3000-01-01'),
	VodUser VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_VodUser DEFAULT(''),
	VodDate DATETIME NOT NULL CONSTRAINT DF_FARIN_OrderMutasi_VodDate DEFAULT('3000-01-01'),

	CONSTRAINT PK_FARIN_OrderMutasi PRIMARY KEY CLUSTERED(OrderMutasiId)
)
GO
