CREATE TABLE FARIN_OrderMutasiBrg
(
	OrderMutasiId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiBrg_OrderMutasiId DEFAULT(''),
	NoUrut INT NOT NULL CONSTRAINT DF_FARIN_OrderMutasiBrg_NoUrut DEFAULT(0),
	BrgId VARCHAR(13) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiBrg_BrgId DEFAULT(''),
	BrgName VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiBrg_BrgName DEFAULT(''),
	Qty DECIMAL(18,0) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiBrg_Qty DEFAULT(0),
	SatuanId VARCHAR(13) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiBrg_SatuanId DEFAULT(''),
	SatuanName VARCHAR(50) NOT NULL CONSTRAINT DF_FARIN_OrderMutasiBrg_SatuanName DEFAULT(''),

	CONSTRAINT PK_FARIN_OrderMutasiBrg PRIMARY KEY CLUSTERED(OrderMutasiId, BrgId)
)
GO
