CREATE TABLE FARPU_KfaReplacement
(
	KfaId VARCHAR(10) NOT NULL CONSTRAINT FARPU_KfaReplacement_KfaId DEFAULT(''),
	KfaNewId VARCHAR(10) NOT NULL CONSTRAINT FARPU_KfaReplacement_KfaNewId DEFAULT(''),
    KfaNewName VARCHAR(512) NOT NULL CONSTRAINT FARPU_KfaReplacement_KfaNewName DEFAULT(''), 
	Reason VARCHAR(128) NOT NULL CONSTRAINT FARPU_KfaReplacement_Reason DEFAULT(''),

	CONSTRAINT PK_FARPU_KfaReplacement_KfaId PRIMARY KEY CLUSTERED(KfaId, KfaNewId)
)