CREATE TABLE FARPU_Kfa
(
	KfaId VARCHAR(10) NOT NULL CONSTRAINT FARPU_Kfa_KfaId DEFAULT(''),
    KfaName VARCHAR(512) NOT NULL CONSTRAINT FARPU_Kfa_KfaName DEFAULT(''), 
	Active BIT NOT NULL CONSTRAINT FARPU_Kfa_Active DEFAULT(0),
	State VARCHAR(10) NOT NULL CONSTRAINT FARPU_Kfa_State DEFAULT(''), 

	KfaTemplateId VARCHAR(10) NOT NULL CONSTRAINT FARPU_Kfa_KfaTemplateId DEFAULT(''),
    KfaTemplateName VARCHAR(512) NOT NULL CONSTRAINT FARPU_Kfa_KfaTemplateName DEFAULT(''), 

	FarmalkesTypeId VARCHAR(10) NOT NULL CONSTRAINT FARPU_Kfa_FarmalkesTypeId DEFAULT(''),
	FarmalkesTypeName VARCHAR(20) NOT NULL CONSTRAINT FARPU_Kfa_FarmalkesTypeName DEFAULT(''),
	FarmalkesTypeGroup VARCHAR(10) NOT NULL CONSTRAINT FARPU_Kfa_FarmalkesTypeGroup DEFAULT(''),
	FarmalkesHsCode VARCHAR(10) NOT NULL CONSTRAINT FARPU_Kfa_FarmalkesHsCode DEFAULT(''),

	Produksi VARCHAR(20) NOT NULL CONSTRAINT FARPU_Kfa_Produksi DEFAULT(''),
	NamaDagang VARCHAR(128) NOT NULL CONSTRAINT FARPU_Kfa_NamaDagang DEFAULT(''),
	Manufacturer VARCHAR(128) NOT NULL CONSTRAINT FARPU_Kfa_Manufacturer DEFAULT(''),
	Registrar VARCHAR(128) NOT NULL CONSTRAINT FARPU_Kfa_Registrar DEFAULT(''),
	NomorIzinEdar VARCHAR(50) NOT NULL CONSTRAINT FARPU_Kfa_NomorIzinEdar DEFAULT(''),
	LkppCode VARCHAR(20) NOT NULL CONSTRAINT FARPU_Kfa_LkppCode DEFAULT(''),

	ControlledDrugId VARCHAR(5) NOT NULL CONSTRAINT FARPU_Kfa_ControlledDrugId DEFAULT(''),
	ControlledDrugName VARCHAR(50) NOT NULL CONSTRAINT FARPU_Kfa_ControlledDrugName DEFAULT(''),
	RutePemberianId VARCHAR(20) NOT NULL CONSTRAINT FARPU_Kfa_RutePemberianId DEFAULT(''),
	RutePemberianName VARCHAR(64) NOT NULL CONSTRAINT FARPU_Kfa_RutePemberianName DEFAULT(''),

	BentukSediaanId VARCHAR(5) NOT NULL CONSTRAINT FARPU_Kfa_BentukSediaanId DEFAULT(''),
	DosePerUnit DECIMAL(18,0) NOT NULL CONSTRAINT FARPU_Kfa_DosePerUnit DEFAULT(0),
	UcumId VARCHAR(10) NOT NULL CONSTRAINT FARPU_Kfa_UcumId DEFAULT(''),
	UcumName VARCHAR(30) NOT NULL CONSTRAINT FARPU_Kfa_UcumName DEFAULT(''),
	UomName VARCHAR(30) NOT NULL CONSTRAINT FARPU_Kfa_UomName DEFAULT(''),

	Generik BIT NOT NULL CONSTRAINT FARPU_Kfa_Generik DEFAULT(0),
	FixPrice DECIMAL(18,2) NOT NULL CONSTRAINT FARPU_Kfa_FixPrice DEFAULT(0),
	HetPrice DECIMAL(18,2) NOT NULL CONSTRAINT FARPU_Kfa_HetPrice DEFAULT(0),

	RxTerm VARCHAR(512) NOT NULL CONSTRAINT FARPU_Kfa_RxTerm DEFAULT(''),
	NetWeight DECIMAL(18,2) NOT NULL CONSTRAINT FARPU_Kfa_NetWeight DEFAULT(0),
	NetWeightName VARCHAR(20) NOT NULL CONSTRAINT FARPU_Kfa_NetWeightName DEFAULT(''),
	Volume DECIMAL(18,2) NOT NULL CONSTRAINT FARPU_Kfa_Volume DEFAULT(0),
	VolumeName VARCHAR(20) NOT NULL CONSTRAINT FARPU_Kfa_VolumeName DEFAULT(''),

	Description VARCHAR(MAX) NOT NULL CONSTRAINT FARPU_Kfa_Description DEFAULT(''),
	Indication VARCHAR(MAX) NOT NULL CONSTRAINT FARPU_Kfa_Indication DEFAULT(''),
	Warning VARCHAR(MAX) NOT NULL CONSTRAINT FARPU_Kfa_Warning DEFAULT(''),
	SideEffect VARCHAR(MAX) NOT NULL CONSTRAINT FARPU_Kfa_SideEffect DEFAULT(''),
	Tags VARCHAR(64) NOT NULL CONSTRAINT FARPU_Kfa_Tags DEFAULT(''),

	CONSTRAINT PK_FARPU_Kfa_KfaId PRIMARY KEY CLUSTERED(KfaId)
)
