CREATE TABLE FARPU_KfaDosageUsage
(
	KfaId VARCHAR(10) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_KfaId DEFAULT(''),
	DisplayName VARCHAR(128) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_DisplayName DEFAULT(''),
	Category VARCHAR(20) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_Category DEFAULT(''),

	BodyWeightMax DECIMAL(18,2) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_BodyWeightMax DEFAULT(0),
	BodyWeightMin DECIMAL(18,2) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_BodyWeightMin DEFAULT(0),

	Duration DECIMAL(18,0) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_Duration DEFAULT(0),
	DurationMax DECIMAL(18,0) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_DurationMax DEFAULT(0),
	DurationUcum VARCHAR(10) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_DurationUcum DEFAULT(''),

	Frequency DECIMAL(18,0) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_Frequency DEFAULT(0),
	FrequencyMax DECIMAL(18,0) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_FrequencyMax DEFAULT(0),
	Period DECIMAL(18,0) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_Period DEFAULT(0),
	PeriodUcum VARCHAR(20) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_PeriodUcum DEFAULT(''),

	Qty DECIMAL(18,0) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_Qty DEFAULT(0),
	QtyHigh DECIMAL(18,0) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_QtyHigh DEFAULT(0),
	QtyUcum VARCHAR(20) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_QtyUcum DEFAULT(''),
	QtyUom VARCHAR(30) NOT NULL CONSTRAINT FARPU_KfaDosageUsage_QtyUom DEFAULT(''),
	UseUcum BIT NOT NULL CONSTRAINT FARPU_Kfa_UseUcum DEFAULT(0),

	CONSTRAINT PK_FARPU_KfaDosageUsage_KfaId PRIMARY KEY CLUSTERED(KfaId, DisplayName)
)