CREATE TABLE FARPU_KfaPackaging
(
	KfaId VARCHAR(10) NOT NULL CONSTRAINT FARPU_KfaPackaging_KfaId DEFAULT(''),
	KfaPackagingId VARCHAR(10) NOT NULL CONSTRAINT FARPU_KfaPackaging_KfaPackagingId DEFAULT(''),
    KfaPackagingName VARCHAR(512) NOT NULL CONSTRAINT FARPU_KfaPackaging_KfaPackagingName DEFAULT(''), 
	PackPrice DECIMAL(18,2) NOT NULL CONSTRAINT FARPU_KfaPackaging_PackPrice DEFAULT(0),
	UomId VARCHAR(50) NOT NULL CONSTRAINT FARPU_KfaPackaging_UomId DEFAULT(''),
	Qty DECIMAL(18,2) NOT NULL CONSTRAINT FARPU_KfaPackaging_Qty DEFAULT(0),
	Generate DECIMAL NOT NULL CONSTRAINT FARPU_Kfa_Generate DEFAULT(0),

	CONSTRAINT PK_FARPU_KfaPackaging_KfaId PRIMARY KEY CLUSTERED(KfaId, KfaPackagingId)
)