CREATE TABLE FARIN_StokBuku(
    StokBukuId VARCHAR(26) NOT NULL CONSTRAINT FARIN_StokBuku_StokBukuId DEFAULT(''),
    StokLayerId VARCHAR(26) NOT NULL CONSTRAINT FARIN_StokBuku_StokLayerId DEFAULT(''),
    NoUrut INT NOT NULL CONSTRAINT FARIN_StokBuku_NoUrut DEFAULT(0),
    BrgId VARCHAR(13) NOT NULL CONSTRAINT FARIN_StokBuku_BrgId DEFAULT(''),
    LayananId VARCHAR(5) NOT NULL CONSTRAINT FARIN_StokBuku_LayananId DEFAULT(''),

    TrsReffId VARCHAR(26) NOT NULL CONSTRAINT FARIN_StokBuku_TrsReffId DEFAULT(''),
    TrsReffDate DATETIME NOT NULL CONSTRAINT FARIN_StokBuku_TrsReffDate DEFAULT('3000-01-01'),
    JenisMutasi VARCHAR(20) NOT NULL CONSTRAINT FARIN_StokBuku_JenisMutasi DEFAULT(''),
    UseCase VARCHAR(20) NOT NULL CONSTRAINT FARIN_StokBuku_UseCase DEFAULT(''),
    QtyIn INT NOT NULL CONSTRAINT FARIN_StokBuku_QtyIn DEFAULT(0),
    QtyOut INT NOT NULL CONSTRAINT FARIN_StokBuku_QtyOut DEFAULT(0),

    EntryDate DATETIME NOT NULL CONSTRAINT FARIN_StokBuku_EntryDate DEFAULT('3000-01-01'),
)