CREATE TABLE FARIN_StokLayer(
    StokLayerId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokLayer_StokLayerId DEFAULT(''),
    BrgId VARCHAR(13) NOT NULL CONSTRAINT DF_FARIN_StokLayer_BrgId DEFAULT(''),
    LayananId VARCHAR(5) NOT NULL CONSTRAINT DF_FARIN_StokLayer_LayananId DEFAULT(''),
    
    TrsInReffId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokLayer_TrsInReffId DEFAULT(''),
    TrsInReffDate DATETIME NOT NULL CONSTRAINT DF_FARIN_StokLayer_TrsInReffDate DEFAULT('3000-01-01'),
    
    PurchaseId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokLayer_PurchaseId DEFAULT(''),
    ReceiveId VARCHAR(26) NOT NULL CONSTRAINT DF_FARIN_StokLayer_ReceiveId DEFAULT(''),
    ExpDate DATETIME NOT NULL CONSTRAINT DF_FARIN_StokLayer_ExpDate DEFAULT('3000-01-01'),
    
    QtyIn INT NOT NULL CONSTRAINT DF_FARIN_StokLayer_QtyIn DEFAULT(0),
    QtySisa INT NOT NULL CONSTRAINT DF_FARIN_StokLayer_QtySisa DEFAULT(0),
    Hpp DECIMAL(18,2) NOT NULL CONSTRAINT DF_FARIN_StokLayer_Hpp DEFAULT(0),
    
    CONSTRAINT PK_FARIN_StokLayer PRIMARY KEY CLUSTERED (StokLayerId)
)